; Pool sized for a readership of two RSS subscribers and one spam bot.
[www]
user = nginx
group = nginx
listen = /run/php-fpm84.sock
listen.owner = nginx
listen.group = nginx
pm = static
pm.max_children = 2
pm.max_requests = 500
